In [3]:
import numpy as np

In [6]:
arr = np.array([ 1,2,3,4])

In [7]:
arr

array([1, 2, 3, 4])

In [8]:
reshaped=arr.reshape(2,2)
reshaped

array([[1, 2],
       [3, 4]])

In [9]:
flattend = reshaped.flatten()
flattend

array([1, 2, 3, 4])

In [10]:
flattend = reshaped.flatten()
flattend[0]=36
flattend

array([36,  2,  3,  4])

In [11]:
arr

array([1, 2, 3, 4])

In [13]:
raveled = reshaped.ravel()
raveled[1]=88
raveled

array([ 1, 88,  3,  4])

In [14]:
arr

array([ 1, 88,  3,  4])

In [15]:
reshaped

array([[ 1, 88],
       [ 3,  4]])

In [4]:
arr1 = np.array ([1,2,3])
print(arr1)
arr2 = np.array ([1,2,3])
print(arr2)

[1 2 3]
[1 2 3]


In [5]:
arr1+arr2

array([2, 4, 6])

In [6]:
arr1+4

array([5, 6, 7])