In [30]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [31]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [32]:
steps=[("standard_Scaler",StandardScaler()),
       ("classifier",LogisticRegression())]

In [33]:
steps

[('standard_Scaler', StandardScaler()), ('classifier', LogisticRegression())]

In [34]:
pipe=Pipeline(steps)

In [35]:
from sklearn import set_config

In [36]:
set_config(display="diagram")

In [37]:
pipe

Pipeline(steps=[('standard_Scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [38]:
from sklearn.datasets import make_classification
X,y=make_classification(n_samples=1000)

In [39]:
X.shape

(1000, 20)

In [40]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.33,random_state=42)

In [41]:
X_train

array([[-0.55933442,  1.31982209, -1.18235703, ..., -0.33947677,
         1.58975749,  1.11511217],
       [-0.47909369,  0.29891867,  2.03135467, ...,  0.24018771,
         0.17555502,  0.36468189],
       [-0.28293558, -0.34392247, -2.17226011, ..., -1.21491195,
        -0.04756635, -0.25996924],
       ...,
       [ 1.57597967,  0.25511117,  2.15982389, ..., -0.88626066,
        -0.41950043,  1.86657933],
       [ 0.73342348, -2.28939486, -0.26165141, ..., -1.62785441,
         0.86428429,  0.13527354],
       [-0.36813065, -0.73472574, -0.10469881, ...,  0.39555924,
         0.34220045,  0.53582429]], shape=(670, 20))

In [42]:
pipe.fit(X_train,y_train)


Pipeline(steps=[('standard_Scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [43]:
 y_pred=pipe.predict(X_test)
 y_pred

array([1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,

In [44]:
 from sklearn.decomposition import PCA
 from sklearn.svm import SVC

In [45]:
steps=[("scaling",StandardScaler()),
      ("PCA",PCA(n_components=3)),
      ("SVC",SVC())]

In [47]:
pipe2=Pipeline(steps)
pipe2.fit(X_train,y_train)

Pipeline(steps=[('scaling', StandardScaler()), ('PCA', PCA(n_components=3)),
                ('SVC', SVC())])

In [48]:
Pipeline(steps=[('scaling', StandardScaler()), ('PCA', 
PCA(n_components=3)),
                ('SVC', SVC())])

Pipeline(steps=[('scaling', StandardScaler()), ('PCA', PCA(n_components=3)),
                ('SVC', SVC())])

In [49]:
 pipe2.predict(X_test)

array([1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,

In [50]:
 from sklearn.impute import SimpleImputer

In [58]:
## numerical processing pipeline
import numpy as np
numeric_processor=Pipeline(

steps=[("imputation_mean",SimpleImputer(missing_values=np.nan,strategy
="mean")),
 ("scaler",StandardScaler())]
)

In [59]:
numeric_processor
Pipeline(steps=[('imputation_mean', SimpleImputer()),
 ('scaler', StandardScaler())])

Pipeline(steps=[('imputation_mean', SimpleImputer()),
                ('scaler', StandardScaler())])

In [60]:
##categorical procesing pipeline
from sklearn.preprocessing import OneHotEncoder

In [61]:
categorical_processor=Pipeline(

steps=[("imputation_consatnt",SimpleImputer(fill_value="missing",strategy="constant")),
 ("onehot",OneHotEncoder(handle_unknown="ignore"))]
)

In [62]:
categorical_processor
Pipeline(steps=[('imputation_consatnt',
 SimpleImputer(fill_value='missing',
strategy='constant')),
 ('onehot', OneHotEncoder(handle_unknown='ignore'))])

Pipeline(steps=[('imputation_consatnt',
                 SimpleImputer(fill_value='missing', strategy='constant')),
                ('onehot', OneHotEncoder(handle_unknown='ignore'))])

In [63]:
## combine processing technqiues
from sklearn.compose import ColumnTransformer

In [64]:
preprocessor=ColumnTransformer(
 [("categorical",categorical_processor,["gender","City"]),
 ("numerical",numeric_processor,["age","height"])]
)

In [65]:
preprocessor

ColumnTransformer(transformers=[('categorical',
                                 Pipeline(steps=[('imputation_consatnt',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'City']),
                                ('numerical',
                                 Pipeline(steps=[('imputation_mean',
                                                  SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 ['age', 'height'])])

In [66]:
from sklearn.pipeline import make_pipeline

In [67]:
 pipe=make_pipeline(preprocessor,LogisticRegression())
 pipe

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('imputation_consatnt',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['gender', 'City']),
                                                 ('numerical',
                                                  Pipeline(steps=[('imputation_mean',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'height'])])),
                ('logisticregression', LogisticRegression())])